import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "IEEECS Recruitments Portal 2024",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-main-bg min-h-screen bg-[url('/back-grid.svg')] bg-cover bg-fixed">{children}</body>
    </html>
  );
}
