import type { Metadata } from "next";
import "./globals.css";
import Nav from "../components/navbar/navbar";
import { Sarpanch } from "next/font/google";
import { AuthProvider } from "@/contexts/auth.context";
export const metadata: Metadata = {
  title: "IEEECS Recruitments Portal 2024",
  description: "Generated by create next app",
};

const sarpanch = Sarpanch({
  weight: ["400", "600"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sarpanch",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${sarpanch.variable}`}>
      <body className="bg-main-bg min-h-screen bg-[url('/back-grid-vertical.svg')] md:bg-[url('/back-grid-horizontal.svg')] bg-cover bg-center bg-fixed">
        <AuthProvider>
          <Nav />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
